dist: xenial
language: python
python:
 - "2.7"
 - "3.7"
matrix:
  include:
    - python: "3.7"
      env: TOXENV=flake8
    - python: "3.7"
      env: TOXENV=docs
install: pip install tox-travis codecov
script: tox -- --with-coverage --cover-branches --cover-package=fedmsg_meta_umb
               --cover-xml --cover-xml-file=$TRAVIS_BUILD_DIR/coverage.xml
after_success: >
  [ -f $TRAVIS_BUILD_DIR/coverage.xml ] &&
  codecov -e TRAVIS_PYTHON_VERSION --file $TRAVIS_BUILD_DIR/coverage.xml || :
